version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    restart: always
    # 如果需要环境变量，可以取消注释以下行
    # environment:
    #   - NODE_ENV=production
    #   - API_URL=https://api.example.com
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 